import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch();
const context=await browser.newContext({viewport:{width:1440,height:1050}});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:4173');
await page.getByRole('heading',{name:/Good morning/}).waitFor();
await fs.mkdir('preview',{recursive:true});
await page.screenshot({path:'preview/desktop.png',fullPage:true});
await page.getByRole('button',{name:'Find your competition',exact:true}).click();
await page.getByLabel('Search tournaments').fill('Guwahati Badminton');
await page.getByRole('button',{name:'Guwahati Badminton Open',exact:true}).click();
await page.getByLabel('I accept the sample rules').check();
await page.getByRole('button',{name:'Continue to demo payment'}).click();
await page.getByRole('button',{name:'Simulate payment & confirm'}).click();
await page.getByRole('heading',{name:'See you on court.'}).waitFor();
await page.getByRole('button',{name:'Go to My events'}).click();
assert.equal(await page.getByText('Demo payment ₹650 · Confirmed').count(),1);
await page.reload();
const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('rally-demo-v1')));
assert.equal(saved.registrations.length,1);
assert.equal(saved.events.find(x=>x.id==='e1').spots,11);
await page.getByRole('button',{name:'Organizer',exact:true}).click();
await page.getByRole('button',{name:'Generate draw',exact:true}).click();
await page.getByRole('heading',{name:'Seeded draw · Open singles'}).waitFor();
await page.getByRole('button',{name:'Approve',exact:true}).first().click();
await page.getByRole('button',{name:'Record result',exact:true}).click();
await page.getByRole('textbox',{name:'Score / result note'}).fill('21–18, 21–16');
await page.getByLabel('I verify this sample result.').check();
await page.getByRole('button',{name:'Publish & update rankings'}).click();
let data=await page.evaluate(()=>JSON.parse(localStorage.getItem('rally-demo-v1')));
assert.equal(data.points,400);assert.equal(data.results.length,1);assert.equal(data.approved.length,1);
await page.getByRole('button',{name:'Create tournament',exact:true}).click();
await page.getByRole('textbox',{name:'Tournament name'}).fill('Demo Weekend Cup');
await page.getByRole('textbox',{name:'Venue',exact:true}).fill('Sample Arena');
await page.locator('input[name="date"]').fill('2026-12-12');
await page.getByRole('button',{name:'Publish demo event'}).click();
data=await page.evaluate(()=>JSON.parse(localStorage.getItem('rally-demo-v1')));
assert.equal(data.events.length,7);
await page.getByRole('button',{name:'Rankings',exact:true}).first().click();
await page.getByRole('button',{name:/Riyan Das.*1,640/}).first().waitFor();
await page.getByRole('button',{name:'Athlete passport',exact:true}).click();
await page.getByRole('button',{name:'Edit profile'}).click();
await page.getByRole('textbox',{name:'Your sporting dream'}).fill('Win the Assam championship');
await page.getByRole('button',{name:'Save passport'}).click();
assert.equal(await page.getByText('“Win the Assam championship”').count(),1);
await page.getByRole('button',{name:'Marketplace',exact:true}).click();
await page.getByRole('button',{name:'Try booking',exact:true}).first().click();
await page.getByRole('button',{name:'Confirm demo booking'}).click();
data=await page.evaluate(()=>JSON.parse(localStorage.getItem('rally-demo-v1')));
assert.equal(data.bookings.length,1);
await page.getByRole('button',{name:'Home',exact:true}).click();
await page.evaluate(async()=>{await navigator.serviceWorker.ready});
await page.waitForTimeout(1500);
await context.setOffline(true);
await page.reload();
await page.getByRole('heading',{name:/Good morning/}).waitFor();
await context.setOffline(false);
assert.equal(errors.length,0,'Browser errors: '+errors.join('; '));
const phone=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const mobile=await phone.newPage();
await mobile.goto('http://localhost:4173');
await mobile.getByRole('heading',{name:/Good morning/}).waitFor();
await mobile.screenshot({path:'preview/mobile.png',fullPage:true});
assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile horizontal overflow');
await mobile.getByRole('button',{name:'Discover',exact:true}).last().click();
await mobile.getByRole('button',{name:'Guwahati Badminton Open',exact:true}).click();
await mobile.screenshot({path:'preview/mobile-event.png'});
assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await mobile.getByRole('button',{name:'Close dialog'}).click();
await mobile.getByRole('button',{name:'Open navigation'}).click();
await mobile.getByRole('button',{name:'Organizer',exact:true}).click();
await mobile.getByRole('heading',{name:'Organizer workspace'}).waitFor();
await mobile.screenshot({path:'preview/mobile-organizer.png',fullPage:true});
const manifest=await (await page.request.get('http://localhost:4173/manifest.webmanifest')).json();
assert.equal(manifest.display,'standalone');assert.equal(manifest.icons.length,3);
console.log('PASS: registration, persistence, spots, draw, approval, results, ranking update, event creation, profile edit, booking, offline reload, mobile navigation, no overflow, manifest, no browser errors.');
await browser.close();
