export const sports=['All sports','Badminton','Tennis','Pickleball','Table Tennis','Running','Football'];
export const initialEvents=[
{id:'e1',name:'Guwahati Badminton Open',sport:'Badminton',city:'Guwahati',date:'2026-10-24',end:'25 OCT',venue:'Nehru Stadium Indoor Arena',fee:650,prize:'₹25,000',spots:12,total:64,image:'badminton',tag:'FILLING FAST',categories:['Open singles','Women’s singles','U-18 singles','Open doubles'],format:'Single elimination',organizer:'Assam Racket Collective',level:'All levels'},
{id:'e2',name:'Brahmaputra Tennis Classic',sport:'Tennis',city:'Guwahati',date:'2026-11-07',end:'08 NOV',venue:'Chachal Tennis Complex',fee:900,prize:'₹40,000',spots:24,total:48,image:'tennis',tag:'RANKED EVENT',categories:['Open singles','U-18 singles','Women’s singles'],format:'Group + knockout',organizer:'Guwahati Tennis Club',level:'Intermediate'},
{id:'e3',name:'Sunday Pickleball Social',sport:'Pickleball',city:'Guwahati',date:'2026-10-18',end:'18 OCT',venue:'Six Mile Community Courts',fee:350,prize:'Medals + good vibes',spots:8,total:32,image:'pickleball',tag:'BEGINNER FRIENDLY',categories:['Mixed doubles','Open doubles'],format:'Round robin',organizer:'Northeast Pickleball',level:'Beginner'},
{id:'e4',name:'Shillong Hills Table Tennis Cup',sport:'Table Tennis',city:'Shillong',date:'2026-11-14',end:'15 NOV',venue:'Polo Indoor Hall',fee:500,prize:'₹15,000',spots:18,total:48,image:'badminton',tag:'NORTHEAST CIRCUIT',categories:['Open singles','U-18 singles'],format:'Double elimination',organizer:'Meghalaya Sports Club',level:'All levels'},
{id:'e5',name:'Run the River 10K',sport:'Running',city:'Guwahati',date:'2026-11-22',end:'22 NOV',venue:'Brahmaputra Riverfront',fee:450,prize:'Finishers medal',spots:86,total:200,image:'running',tag:'COMMUNITY RUN',categories:['10K open','5K community'],format:'Timed race',organizer:'River Runners',level:'All levels'},
{id:'e6',name:'Northeast Futsal Weekend',sport:'Football',city:'Guwahati',date:'2026-12-05',end:'06 DEC',venue:'Game On Sports Arena',fee:2500,prize:'₹30,000',spots:6,total:16,image:'football',tag:'TEAM SPORT PREVIEW',categories:['Open team','College team'],format:'League',organizer:'Game On Guwahati',level:'All levels'}];
export const athletes=[
{id:'a1',name:'Riyan Das',initials:'RD',sport:'Badminton',age:19,category:'Open',city:'Guwahati',academy:'Assam Badminton Academy',points:1240,rating:1628,wins:24,losses:8,rank:3,change:2,color:'#e4edcc',story:'From a borrowed racket to the city top 3.',dream:'Represent Assam at the national championships.',routine:'Two hours on court before college, strength training three evenings a week.'},
{id:'a2',name:'Ananya Bora',initials:'AB',sport:'Badminton',age:17,category:'U-18',city:'Guwahati',academy:'Northeast Sports Academy',points:1580,rating:1742,wins:31,losses:5,rank:1,change:1,color:'#f4d9c9',story:'A school day. A training session. A bigger dream.',dream:'Wear the India jersey one day.',routine:'Six sessions each week, with schoolwork between matches.'},
{id:'a3',name:'Dhruv Sharma',initials:'DS',sport:'Badminton',age:22,category:'Open',city:'Guwahati',academy:'Guwahati Racket Club',points:1420,rating:1689,wins:27,losses:7,rank:2,change:0,color:'#d2e4f0',story:'Finding his way back after an injury.',dream:'Win the Northeast circuit.',routine:'Mobility, footwork and four court sessions a week.'},
{id:'a4',name:'Meghna Deka',initials:'MD',sport:'Tennis',age:20,category:'Open',city:'Guwahati',academy:'Chachal Tennis Academy',points:1360,rating:1660,wins:22,losses:6,rank:1,change:3,color:'#e7d9f0',story:'Building a tennis journey, one early morning at a time.',dream:'Earn a college sports scholarship.',routine:'Morning serves and evening match practice.'},
{id:'a5',name:'Aditya Sen',initials:'AS',sport:'Pickleball',age:25,category:'Open',city:'Shillong',academy:'Hill City Pickleball',points:980,rating:1510,wins:18,losses:6,rank:1,change:4,color:'#ffe6ae',story:'A new sport. A whole new community.',dream:'Bring competitive pickleball to every Northeast city.',routine:'Doubles practice three times a week.'},
{id:'a6',name:'Priya Saikia',initials:'PS',sport:'Badminton',age:21,category:'Open',city:'Guwahati',academy:'Assam Badminton Academy',points:1120,rating:1590,wins:21,losses:9,rank:4,change:1,color:'#d8eae0',story:'Turning consistency into confidence.',dream:'Finish the season in the city top 3.',routine:'Footwork drills, match practice and weekend competition.'}];
export const initialState={role:'Athlete',registrations:[],saved:[],following:[],likes:[],bookings:[],events:initialEvents,approved:[],results:[],draw:false,notifications:[],profile:{name:'Riyan Das',city:'Guwahati',academy:'Assam Badminton Academy',goal:'Represent Assam at the national championships.',consent:false},points:0,disputes:[{id:'d1',text:'Quarterfinal score review · Meghna Deka',status:'Open'}],rankingRules:{winner:400,runner:250,semi:150,participation:40}};
